-- Public, readable numeric IDs. Internal UUID primary/foreign keys remain in
-- place so auth and database relationships keep working safely.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS public_id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.servers
  ADD COLUMN IF NOT EXISTS public_id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.categories
  ADD COLUMN IF NOT EXISTS public_id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.channels
  ADD COLUMN IF NOT EXISTS public_id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.server_roles
  ADD COLUMN IF NOT EXISTS public_id bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS profiles_public_id_uidx ON public.profiles (public_id);
CREATE UNIQUE INDEX IF NOT EXISTS servers_public_id_uidx ON public.servers (public_id);
CREATE UNIQUE INDEX IF NOT EXISTS categories_public_id_uidx ON public.categories (public_id);
CREATE UNIQUE INDEX IF NOT EXISTS channels_public_id_uidx ON public.channels (public_id);
CREATE UNIQUE INDEX IF NOT EXISTS server_roles_public_id_uidx ON public.server_roles (public_id);

COMMENT ON COLUMN public.profiles.public_id IS 'Public numeric profile identifier; internal UUID remains the database key.';
COMMENT ON COLUMN public.servers.public_id IS 'Public numeric server identifier; internal UUID remains the database key.';
COMMENT ON COLUMN public.categories.public_id IS 'Public numeric category identifier; internal UUID remains the database key.';
COMMENT ON COLUMN public.channels.public_id IS 'Public numeric channel identifier; internal UUID remains the database key.';
COMMENT ON COLUMN public.server_roles.public_id IS 'Public numeric role identifier; internal UUID remains the database key.';
